development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  username: postgres
  password: "q1w2e3r4t5y6"
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000
  username: postgres
  password: "q1w2e3r4t5y6"
production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  username: postgres
  password: "q1w2e3r4t5y6"